In [1]:
a = np.array[[2,5,4,9],[23,56,4,8],[56,48,23,25]]

NameError: name 'np' is not defined

In [2]:
import numpy as np

In [3]:
a = np.array[[2,5,4,9],[23,56,4,8],[56,48,23,25]]

TypeError: 'builtin_function_or_method' object is not subscriptable

In [4]:
a = np.array([[2,5,4,9],[23,56,4,8],[56,48,23,25]])

In [5]:
a

array([[ 2,  5,  4,  9],
       [23, 56,  4,  8],
       [56, 48, 23, 25]])

In [9]:
a[1,3]

8

In [10]:
a[0,1]

5

In [8]:
a[0,2]

4

In [11]:
a[1,2]

4

In [12]:
a.shape

(3, 4)

In [13]:
a[2,1:3]

array([48, 23])

In [14]:
a[0:2,2]

array([4, 4])

In [16]:
a[1:2,2:4]

array([[4, 8]])

In [17]:
a[1:,2:]

array([[ 4,  8],
       [23, 25]])

# ARRANGE

In [18]:
list(range(5,100))

[5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99]

In [19]:
np.arange(5,51)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38,
       39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [20]:
np.arange(5.5,55.3)

array([ 5.5,  6.5,  7.5,  8.5,  9.5, 10.5, 11.5, 12.5, 13.5, 14.5, 15.5,
       16.5, 17.5, 18.5, 19.5, 20.5, 21.5, 22.5, 23.5, 24.5, 25.5, 26.5,
       27.5, 28.5, 29.5, 30.5, 31.5, 32.5, 33.5, 34.5, 35.5, 36.5, 37.5,
       38.5, 39.5, 40.5, 41.5, 42.5, 43.5, 44.5, 45.5, 46.5, 47.5, 48.5,
       49.5, 50.5, 51.5, 52.5, 53.5, 54.5])

# RESHAPE

In [24]:
np.arange(12).reshape(6,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [25]:
np.sqrt(91)

9.539392014169456

In [26]:
max(a)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [27]:
a

array([[ 2,  5,  4,  9],
       [23, 56,  4,  8],
       [56, 48, 23, 25]])

In [28]:
a.max

<function ndarray.max>

In [29]:
a.max()

56

In [30]:
a.mean()

21.916666666666668

In [31]:
a.argmax()

5

In [33]:
a*2

array([[  4,  10,   8,  18],
       [ 46, 112,   8,  16],
       [112,  96,  46,  50]])

# RANDOM

In [35]:
np.random.rand(5,6)

array([[0.95770196, 0.37445991, 0.55836753, 0.91507847, 0.90928943,
        0.33413354],
       [0.39341631, 0.51944536, 0.87075951, 0.38657009, 0.65971397,
        0.11321368],
       [0.91829374, 0.68651247, 0.42134185, 0.11831303, 0.04463226,
        0.77040323],
       [0.54645686, 0.55275732, 0.24528484, 0.71626919, 0.14155291,
        0.36049992],
       [0.12026005, 0.55988847, 0.56545041, 0.47179448, 0.93541966,
        0.62973638]])

In [36]:
np.random.randn(2,2)

array([[ 1.32139964, -1.25777396],
       [-1.01050371,  0.3410381 ]])

In [40]:
 b = np.random.randint(9,45,12).reshape(6,2)

In [41]:
b

array([[13, 21],
       [25, 16],
       [16, 15],
       [35, 40],
       [31, 43],
       [42, 13]])

In [42]:
b.sum()

310

In [43]:
b.sum(axis=1)

array([34, 41, 31, 75, 74, 55])

In [44]:
b.sum(axis=0)

array([162, 148])

In [45]:
# 3D

# 3D

In [46]:
c = np.array([[[4,40],[5,50],[6,60]],[[7,70],[8,80],[9,90]],[[5,55],[4,43],[6,66]]])

In [47]:
c

array([[[ 4, 40],
        [ 5, 50],
        [ 6, 60]],

       [[ 7, 70],
        [ 8, 80],
        [ 9, 90]],

       [[ 5, 55],
        [ 4, 43],
        [ 6, 66]]])

In [48]:
d.shape

NameError: name 'd' is not defined

In [49]:
c.shape

(3, 3, 2)

In [50]:
c.reshape(4,3,4)

ValueError: cannot reshape array of size 18 into shape (4,3,4)

# NAN - not a number

In [52]:
x = np.array([12,56,np.nan])

In [53]:
x

array([12., 56., nan])

In [54]:
x.dtype

dtype('float64')